### ISSUE TITLE
In app purchase

### ISSUE THREAD

**Issue by HR** [codexa/SpaceX-Rocket#1]
This app is going to include in app purchases.

**Comment by logan-r** [comment]
Is the app open-source?

**Comment by HR** [comment]
Maybe, but I don't think so.

**Comment by HR** [comment]
I mean we gotta get something for our hard work, right?

**Comment by ferndot** [comment]
This could be a paid app.

**Comment by HR** [comment]
well, if it is on github(free) then who is going to buy it? Either we could have in app purchase or upgrade github membership for private repos.

**Comment by ferndot** [comment]
We would need in-app purchase first.  We could also set it to check for 
an auth certificate on startup (although someone could fork it and 
easily mod it out).

I can't afford a paid plan right now, but if we get some money from app 
purchasers, we can get it eventually.

**Comment by HR** [comment]
The in app-purchase is for different rockets to boost speed and other inventory.

**Comment by ferndot** [comment]
Sounds good, that's how facebook games make their money!

**Comment by logan-r** [comment]
That's fine, I guess.
