### ISSUE TITLE
Music & SFX

### ISSUE THREAD

**Issue by ferndot** [codexa/SpaceX-Rocket#2]
Every game needs background music!

@HRanDEV what style would you like?

**Comment by HR** [comment]
Sci fi, what do you think @Logi0 and @Joshua-S?

**Comment by ferndot** [comment]
I am working on it :)

**Comment by HR** [comment]
What about these:
http://audiojungle.net/item/space-epic/4175770
http://audiojungle.net/item/ambient-dream-space/4681645

I like the second one. It should be an ambient simplistic and relaxing music

**Comment by ferndot** [comment]
Oh, I was going to compose some music.

**Comment by HR** [comment]
No continue, originality and creativity is always preferred. We also don't have to buy it.

**Comment by ferndot** [comment]
I created a new folder on Dropbox called SpaceXRocket media.  The splash sound is in it.  Or, you can see it here: https://www.dropbox.com/s/gzmzxa220bu9m6n/splash.mp3

**Comment by HR** [comment]
Sick man, we could have that for the starting sound. Is it possible that you could maybe compose an ambient sound like this: http://audiojungle.net/item/ambient-dream-space/4681645

**Comment by ferndot** [comment]
Will see :)

**Comment by ferndot** [comment]
@HRanDEV I just did the splash screen, tell me what you think.

**Comment by ferndot** [comment]
Check this out, I will look at the sound you suggested, and compose something like it later.  https://www.dropbox.com/s/1d1yex8l5js4otz/soft.mp3

**Comment by HR** [comment]
Cool, so you're a composer

**Comment by ferndot** [comment]
In my free time :)  Do you play any instruments?

**Comment by HR** [comment]
I used to play the piano, but now, I don't have much time.

**Comment by HR** [comment]
Funny, the time difference between us(I am +5 hours).

**Comment by ferndot** [comment]
So you must be in Europe.

**Comment by HR** [comment]
Yup(Lond)

**Comment by ferndot** [comment]
Awesome, I live in NY.

**Comment by HR** [comment]
C00l

**Comment by logan-r** [comment]
I live in New Jersey.

**Comment by ferndot** [comment]
:) So we are _relatively_ close.  I live in Central New York more specifically.
