### ISSUE TITLE
Storyline

### ISSUE THREAD

**Issue by ferndot** [codexa/SpaceX-Rocket#3]
What is the storyline/idea for this game?  Similar to Galaga?

**Comment by HR** [comment]
I think that it should a Quest that builds up with levels. This game is going to be very oriented around physics such as the gravitational attraction of different sized planets. The unique part of the game is that it is all going to be based on motion controls. And there will be different moods/weather emulated with the environment(as you can see in space.png(s)).

**Comment by ferndot** [comment]
@HRanDEV eventually, we should simulate the environment with webGL.

**Comment by HR** [comment]
Yup

**Comment by HR** [comment]
I am going to draft a story line... you should think about it too

**Comment by ferndot** [comment]
Ok, I will.  (btw, I got 100% or a 5.0 this year on writing.)

**Comment by HR** [comment]
I've been getting A\* for English as well, guess that is why they call us nerds. But as Bill gates said: "Be nice to nerds. Chances are you'll end up working for one."

**Comment by ferndot** [comment]
Yes, we shall rule the world Muhahaha.

<i>One game to rule them all,
One game to bind them,
One game to catch them all,
and in her dark code, bind them.
In the land of 'dexa where the shadow lies!</i>

**Comment by ferndot** [comment]
I just noticed something.  This app is hosted, so it can be tested in the browser and run anywhere, it also doesn't need any privileged APIs :)

**Comment by logan-r** [comment]
Oh well, I got an A- on English. :D

**Comment by ferndot** [comment]
Doesn't matter, you're our star coder!

**Comment by logan-r** [comment]
I haven't been that active lately. :D

**Comment by ferndot** [comment]
It's ok, we all go through times like that ;)

**Comment by ferndot** [comment]
It's called life.

**Comment by HR** [comment]
YOLO
