### ISSUE TITLE
Meaning of "SpaceX-Rocket" and Overview of Story

### ISSUE THREAD

**Issue by HR** [codexa/SpaceX-Rocket#5]
The name of the game represents the basic story. A spacecraft(rocket) has flown to a SpaceX (unknown location/galaxy) that is abstract from the world known. The rocket then has to find its way out back earth. The physics and time(relativity) are different in that space from the space know and there is dark matter everywhere. There will be other obstacles that need to be trespassed. As the game progresses, the levels get harder and space gets more abstract..

**Comment by ferndot** [comment]
Maybe a better idea would be to have it get sucked into a black hole, and be put into a different dimension.  The player then has to find x keys to get back into our dimension.

**Comment by HR** [comment]
Sounds good, I have another great Idea regarding the dimensions; when the device is flat(x-axis) the image is 2d but when the device is portrait(y-axis) then the image will be 3d. So as you tilt the phone the image changes form 2d to 3d, from bird eye view to side-view.

**Comment by Switchblade** [comment]
Sounds cool! I haven't tried it, maybe fuel consumption and refueling stations? Adds a bit of difficulty.

**Comment by ferndot** [comment]
Ya, that might work.
